DROP TABLE MFE_BOARD CASCADE CONSTRAINTS;
DROP TABLE MFE_BOOK CASCADE CONSTRAINTS;
DROP TABLE MFE_CARD CASCADE CONSTRAINTS;
DROP TABLE MFE_CHAT CASCADE CONSTRAINTS;
DROP TABLE MFE_SESSID CASCADE CONSTRAINTS;
DROP TABLE MFE_CONCERT CASCADE CONSTRAINTS;
DROP TABLE MFE_GENRE CASCADE CONSTRAINTS;
DROP TABLE MFE_LIKEY CASCADE CONSTRAINTS;
DROP TABLE MFE_LOCAL CASCADE CONSTRAINTS;
DROP TABLE MFE_MEMBER CASCADE CONSTRAINTS;
DROP TABLE MFE_REPLY CASCADE CONSTRAINTS;
DROP TABLE MFE_REVIEW CASCADE CONSTRAINTS;
DROP TABLE MFE_RECENT_SEARCH CASCADE CONSTRAINTS;

DROP SEQUENCE MFE_BOARD_SEQ;
DROP SEQUENCE MFE_BOOK_SEQ;
DROP SEQUENCE MFE_CARD_SEQ;
DROP SEQUENCE MFE_CHAT_SEQ;
DROP SEQUENCE MFE_CHAT_SEQ2;
DROP SEQUENCE MFE_CONCERT_SEQ;
DROP SEQUENCE MFE_GENRE_SEQ;
DROP SEQUENCE MFE_LIKEY_SEQ;
DROP SEQUENCE MFE_LOCAL_SEQ;
DROP SEQUENCE MFE_RECENT_SEQ;
DROP SEQUENCE MFE_REPLY_SEQ;
DROP SEQUENCE MFE_REVIEW_SEQ;

