DELETE FROM MFE_BOARD;
DELETE FROM MFE_BOOK;
DELETE FROM MFE_CARD;
DELETE FROM MFE_CHAT;
DELETE FROM MFE_SESSID;
DELETE FROM MFE_CONCERT;
DELETE FROM MFE_GENRE;
DELETE FROM MFE_LIKEY;
DELETE FROM MFE_LOCAL;
DELETE FROM MFE_MEMBER;
DELETE FROM MFE_REPLY;
DELETE FROM MFE_REVIEW;
DELETE FROM MFE_RECENT_SEARCH;

DELETE FROM MFE_BOARD_SEQ;
DELETE FROM MFE_BOOK_SEQ;
DELETE FROM MFE_CARD_SEQ;
DELETE FROM MFE_CHAT_SEQ;
DELETE FROM MFE_CHAT_SEQ2;
DELETE FROM MFE_CONCERT_SEQ;
DELETE FROM MFE_GENRE_SEQ;
DELETE FROM MFE_LIKEY_SEQ;
DELETE FROM MFE_LOCAL_SEQ;
DELETE FROM MFE_RECENT_SEQ;
DELETE FROM MFE_REPLY_SEQ;
DELETE FROM MFE_REVIEW_SEQ;

